sudo: false
language: ruby

rvm:
- 2.6
- 2.5
- 2.4
- 2.3
- 2.2
- 2.1
- 2.0
- ruby-head
- jruby-9.2.9.0
- truffleruby

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: truffleruby
    - rvm: 2.3
    - rvm: 2.2
    - rvm: 2.1
    - rvm: 2.0
#   fast_finish: true
