name: Ruby

on: [push]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        ruby: [2.7.x, 2.6.x, 2.5.x, 2.4.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{matrix.ruby}}
    - name: Tests
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake
